#!/usr/bin/env bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2026 Analog Devices, Inc. 

function show_help() {
cat <<EOF
Usage:  ad-r1m mkconfig [-h | --help] [<folder>]

Prepare new bringup configuration.

Options:
  -h, --help       Show this help message.
EOF
}

FOLDER=.
case $1 in
  -h|--help)
    show_help
    exit
    ;;

  *)
    FOLDER="$1"
    ;;
esac

echo "FOLDER=$FOLDER"

mkdir -p "$FOLDER"
cp -ri /usr/share/ad-r1m/default-config/* "$FOLDER"

# Replace symlink to /var/log with an actual folder
rm "$FOLDER"/ros_data/log
mkdir "$FOLDER"/ros_data/log

