include:
  - name: sim
    platforms: '["linux/amd64"]'
    ros_distro: humble
    build_packages: ad_r1m_sim

  - name: robot
    platforms: '["linux/arm64"]'
    ros_distro: humble
    build_packages: ad_r1m_robot

  - name: robot
    platforms: '["linux/arm64"]'
    ros_distro: jazzy
    build_packages: ad_r1m_robot

  # - name: backpack_jetson
  #   platforms: linux/arm64
  #   ros_distro: humble
  #   build_packages: ad_r1m_perception_cuvslam ad_r1m_perception_gmsl
  #   from_image:
