services:
  zenoh_router:
    profiles: [rmw_zenoh_cpp]
    image: $DOCKER_IMAGE
    command: ros2 run rmw_zenoh_cpp rmw_zenohd
    network_mode: host
    ipc: host
    pid: host
    environment:
      - RMW_IMPLEMENTATION

  fastdds_discovery_server:
    profiles: [rmw_fastrtps_cpp]
    image: $DOCKER_IMAGE
    command: fastdds discovery --server-id 0
    network_mode: host
    ipc: host
    pid: host
    environment:
      - RMW_IMPLEMENTATION

  robot:
    image: $DOCKER_IMAGE
    command: ros2 launch ad_r1m_bringup bringup.launch.py namespace:="${ROBOT_NAMESPACE:-/}" can_iface:=can0 sensor_fusion:=true
    network_mode: host
    ipc: host
    pid: host
    cap_add: [NET_ADMIN, SYS_PTRACE, SYS_ADMIN]
    security_opt:
      - seccomp:unconfined
    privileged: true
    volumes:
      - /dev/ttyCRSF:/dev/ttyCRSF
      - /sys/kernel/debug/:/sys/kernel/debug/
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  tof:
    image: $DOCKER_IMAGE
    command: |
      ros2 launch ad_r1m_perception_aditof depthimage_to_laserscan.launch.py ${ROBOT_NAMESPACE:+namespace:=}${ROBOT_NAMESPACE}
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  teleop_crsf:
    image: $DOCKER_IMAGE
    command: |
      ros2 launch ad_r1m_bringup teleop_crsf.launch.py namespace:="${ROBOT_NAMESPACE:-/}" params_file:="/ros_data/teleop_parameters.yaml"
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    volumes:
      - /dev/ttyCRSF:/dev/ttyCRSF
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  # One-off actions, run with `docker compose run ...`
  teleop_keyboard:
    profiles: [oneoff]
    image: $DOCKER_IMAGE
    command: ros2 run ad_r1m_bringup teleop_keyboard.py --ros-args --params-file /ros_data/teleop_parameters.yaml -r __ns:="${ROBOT_NAMESPACE:-/}"
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  shell:
    profiles: [oneoff]
    image: $DOCKER_IMAGE
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  save_map:
    profiles: [oneoff]
    image: $DOCKER_IMAGE
    command: bash -c "ros2 run nav2_map_server map_saver_cli -f /ros_data/map_$(date -Is -u)" --fmt png
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  # AMCL based localization profile. Select with `docker compose --profile loc_amcl ...`
  localization_amcl:
    profiles: [loc_amcl]
    image: $DOCKER_IMAGE
    command: ros2 launch ad_r1m_navigation localization_launch.py map:=/ros_data/map.yaml
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  # Blind (empty map) localization profile. Select with `docker compose --profile loc_blind ...`
  localization_blind:
    profiles: [loc_blind]
    image: $DOCKER_IMAGE
    command: bash -c 'ros2 run tf2_ros static_transform_publisher --x 0 --y 0 --z 0 --yaw 0 --pitch 0 --roll 0 --frame-id map --child-frame-id $${ROBOT_NAMESPACE#/}odom'
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
      - ROBOT_NAMESPACE
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  # Map server for dead-reckoning localization. Runs together with localization_blind.
  map_server:
    profiles: [loc_blind]
    image: $DOCKER_IMAGE
    command: ros2 launch ad_r1m_navigation map_server_launch.py map:=/ros_data/maps/empty300.yaml
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  # Navigation profile. Select with `docker compose --profile nav ...`
  nav:
    profiles: [nav]
    image: $DOCKER_IMAGE
    command: ros2 launch ad_r1m_navigation navigation_launch.py
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  # Mapping profile. Select with `docker compose --profile slam ...`
  slam:
    profiles: [slam]
    image: $DOCKER_IMAGE
    command: ros2 launch ad_r1m_navigation online_async_launch.py
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  # Individual services for motor ccontrol, sensors and tools. Development and debugging purposes. Select with `docker compose --profile <service> ...`
  # Motor control service. Select with `docker compose --profile motors ...`
  motors:
    profiles: [motors]
    image: $DOCKER_IMAGE
    command: ros2 launch ad_r1m_bringup ad_r1m_control drive_control.launch.py namespace:="${ROBOT_NAMESPACE:-/}" can_iface:=can0
    network_mode: host
    ipc: host
    pid: host
    cap_add: [NET_ADMIN, SYS_PTRACE]
    security_opt:
      - seccomp:unconfined
    privileged: true
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  # EKF sensor fusion service. Runs together with motors, published odom->base_link transform.
  sensor_fusion:
    profiles: [motors]
    image: $DOCKER_IMAGE
    command: ros2 launch ad_r1m_bringup ad_r1m_control sensor_fusion.launch.py namespace:="${ROBOT_NAMESPACE:-/}" ekf_config_file:=/ros_data/ekf.yaml
    network_mode: host
    ipc: host
    pid: host
    cap_add: [NET_ADMIN, SYS_PTRACE]
    security_opt:
      - seccomp:unconfined
    privileged: true
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false

  # IMU service. Select with `docker compose --profile imu ...`
  imu:
    profiles: [imu]
    image: $DOCKER_IMAGE
    command: ros2 launch ad_r1m_bringup imu.launch.py namespace:="${ROBOT_NAMESPACE:-/}"
    network_mode: host
    ipc: host
    pid: host
    privileged: true # for sysfs
    volumes:
      - ./ros_data:/ros_data
      - ./ros_data/log:/root/.ros/log
    environment:
      - RMW_IMPLEMENTATION
    depends_on:
      zenoh_router:
        condition: "service_started"
        required: false
