# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Analog Devices Inc.
#
# Dispatcher workflow for docker builds, tests, and optionally pushes.
# See docker_build_test_push.yml for the underlying logic.

name: Docker build, test, push
on:
  pull_request:      # Run tests on all PRs
  push:
    branches:
      - '**'         # Run tests on all branches
      - 'main'       # Deploy nightly from the main branch
    tags:
      - '*.*.*'      # Deploy release from semver tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
  REGISTRY: docker.cloudsmith.io/adi/adrd-common

jobs:
  setup:
    runs-on: ubuntu-slim
    outputs:
      tag_suffixes: ${{ steps.vars.outputs.tag_suffixes }}
      docker_target: ${{ steps.vars.outputs.docker_target }}
      docker_push: ${{ steps.vars.outputs.docker_push }}
      full_version: ${{ steps.vars.outputs.full_version }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          v_major=$(cut -d. -f1 <VERSION)
          v_minor=$(cut -d. -f2 <VERSION)
          v_patch=$(cut -d. -f3 <VERSION)

          docker_target=tester
          docker_push=false
          suffix="-${{ github.ref_name }}"
          suffix="${suffix//[^-_a-zA-Z0-9]/-}"

          if ${{ github.ref_type == 'tag' }}; then
            echo "Release ${v_major}.${v_minor}.${v_patch}"
            docker_target=runner
            docker_push=true
            suffix=""
          elif ${{ github.ref == 'refs/heads/main' }}; then
            echo "Nightly pre-release ${v_major}.${v_minor}.${v_patch}"
            docker_target=dev
            docker_push=true
            suffix="-nightly"
          elif ${{ github.event_name == 'pull_request' }}; then
            echo "Test PR #${{ github.event.pull_request.number }}"
            docker_target=tester
            docker_push=false
            suffix="-pr-${{ github.event.pull_request.number }}"
          else
            echo "Test ref ${{ github.ref_name }}"
          fi

          tag_suffixes="${suffix}" # ...-nightly
          tag_suffixes="${tag_suffixes},-${v_major}${suffix}" # ...-1-nightly
          tag_suffixes="${tag_suffixes},-${v_major}.${v_minor}${suffix}" # ...-1.2-nightly
          tag_suffixes="${tag_suffixes},-${v_major}.${v_minor}.${v_patch}${suffix}" # ...-1.2.3-nightly

          {
            echo "tag_suffixes=$tag_suffixes"
            echo "docker_target=$docker_target"
            echo "docker_push=$docker_push"
            echo "full_version=${v_major}.${v_minor}.${v_patch}${suffix}"
          } >> "$GITHUB_OUTPUT"

  docker_test_build_push:  
    strategy:
      fail-fast: false
      matrix:
        include:
        # ioan 2026-06-06: The ad-r1m:{sim,robot}-{distro} naming is legacy which I am strongly
        #                  considering deprecating in favor of {metapackage}:{distro}
        #                  e.g. ad_r1m_robot:humble instead of ad-r1m:robot-humble
        - { name: "ad-r1m", tag_prefix: "sim-humble",   build_packages: "ad_r1m_sim",   ros_distro: "humble",   platforms: '["linux/amd64"]'}
        - { name: "ad-r1m", tag_prefix: "robot-humble", build_packages: "ad_r1m_robot", ros_distro: "humble",   platforms: '["linux/arm64"]'}
        - { name: "ad-r1m", tag_prefix: "robot-jazzy",  build_packages: "ad_r1m_robot", ros_distro: "jazzy",    platforms: '["linux/arm64"]'}

    needs: [setup]
    name: Docker ${{ matrix.name }}:${{ matrix.tag_prefix }}
    uses: ./.github/workflows/_docker_build_test_push.yml
    secrets: inherit
    with:
      name: ${{ matrix.name }}
      build_packages: ${{ matrix.build_packages }}
      ros_distro: ${{ matrix.ros_distro }}
      platforms: ${{ matrix.platforms }}
      docker_target: ${{ needs.setup.outputs.docker_target }}
      docker_push: ${{ needs.setup.outputs.docker_push == 'true' }} # Convert str to bool
      tag_prefix: ${{ matrix.tag_prefix }}
      tag_suffixes: ${{ needs.setup.outputs.tag_suffixes }}
      full_version: ${{ needs.setup.outputs.full_version }}
