on:
  pull_request:
  push:
    tags: ['*.*.*']

permissions:
  contents: read
  id-token: write

env:
  REGISTRY: docker.cloudsmith.io/adi/adrd-common

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag_suffixes: ${{ steps.vars.outputs.tag_suffixes }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          v_major=$(cut -d. -f1 <VERSION)
          v_minor=$(cut -d. -f2 <VERSION)
          v_patch=$(cut -d. -f3 <VERSION)
          nightly=${{ github.ref_type != 'tag' && '-nightly' || '' }}

          {
            echo "tag_suffixes<<EOF"
            echo "${nightly}"
            echo "-${v_major}${nightly}"
            echo "-${v_major}.${v_minor}${nightly}"
            echo "-${v_major}.${v_minor}.${v_patch}${nightly}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  docker:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ad_r1m_sim
            build_packages: ad_r1m_sim
            ros_distro: humble
            platforms: '["linux/amd64"]'
          - name: ad_r1m_robot
            build_packages: ad_r1m_robot
            ros_distro: humble
            platforms: '["linux/arm64"]'
          - name: ad_r1m_robot
            build_packages: ad_r1m_robot
            ros_distro: jazzy
            platforms: '["linux/arm64"]'
    uses: ./.github/workflows/docker_test_build_push.yml
    secrets: inherit
    with:
      name: ${{ matrix.name }}
      platforms: ${{ matrix.platforms }}
      ros_distro: ${{ matrix.ros_distro }}
      build_packages: ${{ matrix.build_packages }}
      target: ${{ github.ref_type == 'tag' && 'runner' || 'dev' }}
      push: ${{ github.ref_type == 'tag' || github.ref == 'refs/heads/main' }}
      tag_suffixes: ${{ needs.setup.outputs.tag_suffixes }}
