on:
  pull_request:
    types: [closed]

jobs:
  clean-gh-pages:
    runs-on: ubuntu-latest
    concurrency:
      group: gh-pages
    permissions:
      contents: write

    steps:
    - uses: analogdevicesinc/doctools/gh-pages-rm-path@9f2ae9d124e9af79026d3d7096bcfae93538499b
      with:
        path: pull/${{ github.event.number }}

